name: Day chuyen Docker tu dong

on:
  push:
    branches:
      - main

jobs:
  dong_goi_va_xuat_xuong:
    runs-on: ubuntu-latest
    steps:
      - name: Buoc 1 - Thay quan ao (Lay code ve)
        uses: actions/checkout@v3

      - name: Buoc 2 - Trinh the can cuoc (Dang nhap Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buoc 3 - Dong hop Java (Build Docker)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-app-senior:latest .

      - name: Buoc 4 - Cho hang ra Tong kho (Push len Docker Hub)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app-senior:latest
